- pom.xml
Currently, some of the tools that rely on JDom2 to import XML (e.g. TrackMate & MaMuT) generate an exception with JDom 2.0.5.
Example in MaMuT:
```
java.lang.ExceptionInInitializerError
at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:338)
at org.jdom2.input.SAXBuilder.<init>(SAXBuilder.java:221)
at fiji.plugin.trackmate.io.TmXmlReader.<init>(TmXmlReader.java:168)
at fiji.plugin.mamut.io.MamutXmlReader.<init>(MamutXmlReader.java:33)
at fiji.plugin.mamut.LoadMamutAnnotationPlugin.load(LoadMamutAnnotationPlugin.java:68)
at fiji.plugin.mamut.LoadMamutAnnotationPlugin.run(LoadMamutAnnotationPlugin.java:61)
at ij.IJ.runUserPlugIn(IJ.java:212)
at ij.IJ.runPlugIn(IJ.java:176)
at ij.Executer.runCommand(Executer.java:132)
at ij.Executer.run(Executer.java:65)
at …
```
> Update jdom2 to v2.0.6.

- pom.xml
This version of the pom.xml adds a "findbugs profile" which relies on Findbugs for static code analysis and bug checking. Findbugs performs static code on compiled class file and writes a report. 
At current state, if findbugs reports bugs will not block the build process. It could be possible to turn true the failOnError attribute, but it is better to leave it on false due to possible false positive checked by Findbugs.
If someone is interested in Findbugs project, you can check more here: http://findbugs.sourceforge.net/
An Eclipse plugin is also available.
> Adding finfbugs profile

- pom.xml
An issue with a NPE has been fixed in 1.0-beta-4 when using M2E.
> POM: bump extra-enforcer-rules version

- pom.xml
Following Bio-Formats 5.2.0 release, this bumps the `bioformats.version` in the scijava pom as discussed in https://github.com/openmicroscopy/bioformats/pull/2482#discussion_r74788623
> Bump Bio-Formats version to 5.2.0

- pom.xml
Fixes #26
This commit bumps the Bio-Formats dependencies in pom-scijava following the 5.3.0 release. As a result of the component architecture and decoupling, the low-level ome-common and ome-xml have their version number now maintained independently of bio-formats.version and their groupId is adjusted.
> Update pom-scijava post Bio-Formats 5.3.0

- pom.xml
Bumping the Bio-Formats version to 5.7.2 following the latest release.
See http://forum.imagej.net/t/release-of-bio-formats-5-7-2/7999
> Bump Bio-Formats version to 5.7.2

- pom.xml
Changes released in `org.openmicroscopy:ome-common:5.3.3` caused TIFF writing failures when tested internally in Bio-Formats and got reverted in `org.openmicroscopy:ome-common:5.3.4` 
References:
- https://trello.com/c/OimiHAQY/175-profile-tiff-writing-on-windows
- https://www.openmicroscopy.org/community/viewtopic.php?f=13&t=8441
- https://github.com/ome/ome-common-java/pull/21
> Bump ome-common to 5.3.4

- pom.xml
These artifacts are used in several components now, e.g. `imagej-legacy`, `imglib2`, `scijava-benchmarks`, `imagej-benchmarks`, and others.
> Add jmh-core and jmh-generator-annprocess

- pom.xml
Bumping Bio-Formats version to 6.1.0 and ome-common to 6.0.3
See release notes at https://www.openmicroscopy.org/2019/05/20/bio-formats-6-1-0.html
> Bump Bio-Formats version to 6.1.0

- pom.xml
Bumping the Bio-Formats version to the latest - 6.1.1
See release notes at https://www.openmicroscopy.org/2019/06/12/bio-formats-6-1-1.html
> Bump Bio-Formats version to 6.1.1

- pom.xml
* imglib2-realtransform: 2.1.0 -> 2.2.1
* bigwarp: 3.1.2 -> 4.0.0
* jitk-tps: 3.0.0 -> 3.0.1
> Update component versions - bigwarp major release

- pom.xml
Bumping the Bio-Formats version to the latest - 6.2.1
See release notes at https://www.openmicroscopy.org/2019/08/29/bio-formats-6-2-1.html
> Bump Bio-Formats version to 6.2.1

- pom.xml
See https://forum.image.sc/t/release-of-bio-formats-6-3-0/30777
This release increments the minor version, most of the changes revolve around reader implementations and a couple of backwards compatible API were introduced. As such, it should not have any breaking impact on consumers of pom-scijava.
> Bump Bio-Formats version to 6.3.0

- pom.xml
* imagej-scijava-plugins-uploader-webdav: 0.2.2 -> 0.3.1
* imagej-ui-swing: 0.22.0 -> 0.23.1
* imagej-updater: 0.9.3 -> 0.10.1
This is the first stage of a new updater - a version which checks the Java support of our HTTPS certificate and changes the URLs of update sites depending on that. It can also handle changes to URLs on the list of available update sites (in the original version these changes were ignored). Changes to an activated update site URL always have to be approved by the user before they are applied.
More info: https://imagej.net/UpdaterV1
> Updater V1 changes

- pom.xml
Would it be possible to update to the more recent miglayout 5.2. This will require adding miglayout-core as an additional jar because now it is a dependency of miglayout-swing.
We are developing a javafx gui that uses the miglayout-javafx and this change will allow compatibility. Maybe miglayout-javafx should also be added, but I am not sure if other projects use it.
I have tested this update on my local Fiji and haven't see any issues. We are happy to perform any specific tests that might reveal issues.
> update miglayout version

- pom.xml
* Bump versions of N5-related artifacts
* Remove some of the Google Cloud SDK dependencies that are not needed anymore in newer `n5-google-cloud`
* Downgrade `jackson-databind` because Spark and AWS SDK still use an older version and were producing runtime errors if running with the newer version
> Update N5 configuration

- pom.xml
This fixes backwards compatibility issues described in https://github.com/axtimwalde/mpicbg/issues/53
> Bump mpicbg to 1.4.0

- pom.xml
This requires https://github.com/scijava/scijava-io-http/pull/5 to be accepted and merged!
> Bump scijava-io-http to version 0.2.1

- pom.xml
`scijava-optional` is used in `imglib2-cache` now, so we should manage it in `pom-scijava`:
https://github.com/imglib/imglib2-cache/pull/14
/cc @tpietzsch
> Add scijava-optional

- pom.xml
[Eclipse Collections](https://www.eclipse.org/collections/) is a Java collections framework containing useful and high performance replacements for JDK's default collections. For example, HashSet<Integer> can be replaced by the primitive collection IntHashSet. It is in general faster than Trove by a factor of 1.5-3×, and is actively maintained at [https://github.com/eclipse/eclipse-collections](https://github.com/eclipse/eclipse-collections).
> Add Eclipse Collections

- pom.xml
I'm not sure which components other than [`saalfeldlab/bigwarp`](https://github.com/saalfeldlab/bigwarp) make use of OpenCSV. The basic usage of `CSVReader` and `CSVWriter` doesn't seem to be affected.
API changes can be browsed at https://abi-laboratory.pro/?view=timeline&lang=java&l=opencsv.
/cc @bogovicj
> Update OpenCSV version: 3.9 -> 5.2

- pom.xml
Bumping to the latest minor release of Bio-Formats.
https://forum.image.sc/t/release-of-bio-formats-6-6-0/46644 for details of what is included
Note that this includes the kyro dependency bumps from https://github.com/ome/ome-common-java/pull/50 and https://github.com/ome/bioformats/pull/3557
We have also added a new reader which requires an additional dependency of `sqlite-jdbc` version 3.28.0 (https://github.com/ome/bioformats/pull/3637/files#diff-163d06c24353c2092cb730eb800f3df44cf4db6ea72c5fcdf63b1c3e8f741274). Would it be possible to get this additional dependency included also?
> Bump Bio-Formats version to 6.6.1

- pom.xml
The `sc.fiji:Stitching_` artifact was recently updated by @StephanPreibisch and already uploaded to the update site, but `pom-scijava` was not yet updated to reflect these changes.
> POM: update Stitching version

- pom.xml
Bumping to the latest minor release of Bio-Formats.
https://forum.image.sc/t/release-of-bio-formats-6-8-0/60895 for details on what all is included
One particular note on some of the dependencies bumps:
- we have bumped jhdf5 to version 19.04.0
- we have bumped commons-lang to version 2.6
- we have added a new dependency to support zstd compression for CZI files
```
<groupId>io.airlift</groupId>
<artifactId>aircompressor</artifactId>
<version>0.18</version>
```
> Bump Bio-Formats version to 6.8.1

- pom.xml
@ctrueden I added CLIJ and Labkit dependencies as discussed previously.
CLIJ versions are the same as currently in the CLIJ parent pom and on the update site.
Newest Labkit versions.
Newest version of BridJ, apache commons pool2-and jocl.
@haesleinhuepf
> Add Labkit and CLIJ

- pom.xml
Bumping to the latest minor release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-9-0/63775 for full details of the changes included.
> Bump Bio-Formats version to 6.9.0

- pom.xml
Bumping to the latest patch release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-9-1/65985 for full details of the changes included.
> Bump Bio-Formats version to 6.9.1

- pom.xml
Bumping to the latest minor release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-10-0/67720 for full details of the changes included.
This includes a number of component updates, most notably:
```
logback-core was upgraded to 1.2.9
logback-classic was upgraded to 1.2.9
xercesImpl was upgraded to 2.12.2
xml-apis was upgraded to 1.4.01
snakeyaml 1.29 was added as a dependency
```
> Bump Bio-Formats version to 6.10.0

- pom.xml
Bumping to the latest minor release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-10-1/70711 for full details of the changes included.
> Bump Bio-Formats version to 6.10.1

- pom.xml
Bumping to the latest minor release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-11-0/72733 for full details of the changes included.
> Bump Bio-Formats version to 6.11.0

- pom.xml
This bring improvements across the board to the script editor
(NB: there has been a tiny change in the rsyntaxtextarea API, and https://github.com/scijava/script-editor/pull/64 will be required to compile the script editor under these versions).
> Update rsyntaxtextarea components to v3.3.0

- pom.xml
This brings bug fixes, MacOS 'native' themes, and [JetBrains Mono](https://www.jetbrains.com/lp/mono/), the coding font used by JetBrains software.
> Update FlatLaf to v3.1.1 + Jetbrains Mono

- pom.xml
Bumping to the latest patch release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-13-0/80689 for full details of the changes included. This includes the dependency bumps from https://github.com/ome/bioformats/issues/3970 to bring Bio-Formats up to date with the changes discussed in https://forum.image.sc/t/plugin-maintainers-can-you-test-fiji-2-11-0/78852/14
> Bump Bio-Formats version to 6.13.0

- pom.xml
Bumping to the latest release of Bio-Formats, which includes a number of dependency updates. See [here](https://forum.image.sc/t/release-of-bio-formats-7-1-0/89725) for full details of the changes included.
> Bump Bio-Formats version to 7.1.0

- pom.xml
> bump n5, bigdataviewer, bigwarp versions

- pom.xml
- rules.xml
This PR bumps Jackson and its dependents to the current version, 2.16.1. It also removes the warning about not changing the version, as the issue seems to be gone with this new version.
> Bump Jackson and dependents to 2.16.1

- pom.xml
Mockito 4.11.0 is the last version that supports Java 8. The previous version stopped working with Maven, Eclipse, etc.
> Update pom.xml to use Mockito 4.11.0

- pom.xml
bugfix version bump of imglib2-label-multisets from `0.13.0` -> `0.13.1`
> bump imglib2-label-multiset for bugfix

- pom.xml
There is a new release of scijava-ui-swing: https://maven.scijava.org/#nexus-search;gav~org.scijava~scijava-ui-swing~1.0.2~~
Thus the version of scijava-ui-swing could be updated.
> Update scijava-ui-swing version to newest release 1.0.2

- pom.xml
- tests/run.sh
* should address mega-melt issues
> bump n5-ij, n5-viewer, bigwarp

- pom.xml
Dependencies that were upgraded in 8.1.0 have also been updated to match here, see https://bio-formats.readthedocs.io/en/stable/about/whats-new.html#february.
Relevant changelogs for other updated dependencies:
- ome-common-java: https://github.com/ome/ome-common-java/releases/tag/v6.0.25
- ome-codecs: https://github.com/ome/ome-codecs/releases/tag/v1.1.0
- ome-metakit: https://github.com/ome/ome-metakit/releases/tag/v5.3.8
- ome-model: https://github.com/ome/ome-model/releases/tag/v6.4.0
The logback dependency intentionally hasn't been changed here, but note Bio-Formats 8.1.0 uses logback 1.3.15.
> Update to Bio-Formats 8.1.0

- pom.xml
- tests/generate-mega-melt.py
Our plugin Mars uses Jackson a lot for basically all file storage. We use smile encoding to decrease the size of json files. Would it be possible to manage jackson-dataformat-smile in pom-scijava? This pull request adds it.
I noticed now the jackson jars are coming with Fiji, except for jackson-dataformat-smile. Also, this now created some version skew with our update site that is still at 2.11. I am in the process of fixing that and maybe I could just remove the Jackson jars from our update site. But then would it also be possible to add the jackson-dataformat-smile jar to Fiji? I know that adds more bloat
Already managing the version here would help.
> add jackson-dataformat-smile to pom

- pom.xml
bumps some recently released N5 library versions
- `n5`
- `n5-aws-s3`
- `n5-google-cloud`
- `n5-ij`
- `n5-zarr`
- `n5-universe`
> n5 library version bumps

- pom.xml
See https://bio-formats.readthedocs.io/en/stable/about/whats-new.html#may.
The only dependency update was `sqlite-jdbc`, which is not defined separately here.
> Update to Bio-Formats 8.2.0

- pom.xml
Updates BoneJ to 7.1.1, which includes the new bonej-plus package for GPU accelerated processing
> BoneJ v7.1.1
