pom.xml

Following http://forum.imagej.net/t/release-of-bio-formats-5-3-2/3690

Bump Bio-Formats to version 5.3.2

---

pom.xml

Also included the minor version increment of the ome-xml component to 5.4.0

Bump Bio-Formats to version 5.3.4

---

pom.xml

Following the public release - see http://forum.imagej.net/t/release-of-bio-formats-5-4-0/4543/1

Bump Bio-Formats version to 5.4.0

---

pom.xml

Update ImageJ 1.x version from 1.51k to 1.51m.

Update ImageJ 1.x version

---

pom.xml

Update opencsv version and groupId

---

pom.xml

* imglib2: 4.6.0 -> 4.6.1
* imglib2-algorithm: 0.8.1 -> 0.8.2
* imglib2-algorithm-fft: 0.1.4 -> 0.1.5
* imglib2-algorithm-gpl: 0.2.1 -> 0.2.2
* imglib2-ij: 2.0.0-beta-38 -> 2.0.0-beta-39

Update component versions

---

pom.xml

See https://www.openmicroscopy.org/2018/02/21/bio-formats-5-8-0.html

Bump Bio-Formats to 5.8.0

---

pom.xml

- `scijava/batch-processor`
- `scijava/ui-behaviour`

Add missing SciJava components

---

pom.xml

See https://www.openmicroscopy.org/2018/03/22/bio-formats-5-8-1.html

Bump Bio-Formats to 5.8.1

---

pom.xml

See https://www.openmicroscopy.org/2018/04/23/bio-formats-5-8-2.html

Bump Bio-Formats to 5.8.2

---

pom.xml

In my opinion the best Java command line parser
http://picocli.info/

Add picocli

---

pom.xml

See https://forum.image.sc/t/release-of-bio-formats-5-9-1/19048

Bump Bio-Formats to version 5.9.1

---

pom.xml

As the minor version was increased in 9acc0a3a3581276e3e1c11cc43e16c4c27391ac5, no additional version change is required.

Add scijava-table

---

pom.xml

Also bump `batch-processor` version: 0.1.3 -> 0.2.0

Add imagej-plugins-batch

---

pom.xml

See https://forum.image.sc/t/release-of-bio-formats-5-9-2/19448/2

Bump Bio-Formats and dependency versions

---

pom.xml

As discussed with @imagejan here: https://forum.image.sc/t/circular-dependency-of-jars/19664/15

Manage snakeyaml and snakeyaml-engine

---

pom.xml

Announced on the image.sc forum as https://forum.image.sc/t/release-of-bio-formats-6-0-0/23099

Bump Bio-Formats versions to 6.0.0

---

pom.xml

maven.imagej.net -> maven.scijava.org

Bump to pom-scijava-base 6.0.0

---

pom.xml

use Descriptor_based_registration 2.1.4

---

pom.xml

* imagej-tensorflow is depending on `commons-compress`

Adds commons-compress to managed dependencies

---

pom.xml

including dependencies that are used by the n5 projects for future dependency management

add n5 related dependencies

---

pom.xml

Bumping to the latest patch release of Bio-Formats.
See https://forum.image.sc/t/release-of-bio-formats-6-3-1/32320 for details of what is included

Bump Bio-Formats version to 6.3.1

---

pom.xml

Bumping to the latest patch release of Bio-Formats.
See https://forum.image.sc/t/release-of-bio-formats-6-4-0/34986 for details of what is included

Bump Bio-Formats version to 6.4.0

---

pom.xml

Bumping to the latest minor release of Bio-Formats.
See https://forum.image.sc/t/release-of-bio-formats-6-5-0/37266 for details of what is included

Bump Bio-Formats version to 6.5.0

---

pom.xml

This PR introduces a common version of JUnit 5.

Add versions for JUnit 5 modules

---

pom.xml

Released BoneJ 7.0.6 today: 
https://github.com/bonej-org/BoneJ2/releases/tag/bonej-7.0.6

Update BoneJ version to 7.0.6

---

pom.xml

dependencies of n5-blosc and n5-google-cloud, respectively

add jblosc and google-cloud-nio

---

pom.xml

... to fix `list : no such field`
See https://github.com/bigdataviewer/bigdataviewer-vistools/issues/46 and https://github.com/bigdataviewer/bigdataviewer-core/pull/103

Update  bigdataviewer-vistools to 1.0.0-beta-21

---

pom.xml

newer ui-behaviour includes some fixes and clean ups in its GUI key-bindings editor

update ui-behaviour 2.0.1 -> 2.0.3

---

pom.xml

- Remove ca.mcgill.Sholl_Analysis as it is now part of SNT
- Replace legacy sc.fiji.Simple_Neurite_Tracer with org.morphonets.SNT

Update SNT related components

---

pom.xml

* n5
* n5-aws-s3
* n5-google-cloud
* n5-hdf5
* n5-ij
* n5-viewer_fiji
* n5-zarr

update n5 artifact versions, add n5-ij

---

pom.xml

* n5 > 2.5.0
* n5-google-cloud > 3.3.2
* n5-hdf5 > 1.3.0
* n5-ij > 2.0.0
* n5-imglib2 > 4.0.0
* n5-viewer_fiji > 4.2.1

bump n5 components

---

pom.xml

Bumping to the latest minor release of Bio-Formats.
https://forum.image.sc/t/release-of-bio-formats-6-7-0/56735 for details of what is included

Bump Bio-Formats version to 6.7.0

---

pom.xml

bigdataviewer-core  --> 10.2.1
bigdataviewer-vistools --> 1.0.0-beta-29

Bump bigdataviewer components

---

pom.xml

Update Trainable Segmentation version

---

pom.xml

* n5-imglib2 4.3.0
* n5-ij 3.2.0
* n5-viewer_fiji 4.5.0
* n5-zarr 0.0.7

Update n5 artifact versions

---

pom.xml

This is the first step of solving scijava/scijava#57
TODOS:

Add Therapi-runtime-javadoc

---

pom.xml

https://github.com/bonej-org/BoneJ2/releases/tag/bonej-7.0.13

bonej-7.0.13

---

pom.xml

ui-behaviour -> 2.0.6
bigdataviewer-core -> 10.4.1
bigdataviewer-vistools -> 1.0.0-beta-30

Bump bigdataviewer versions

---

pom.xml

This should fix https://github.com/bigdataviewer/bigdataviewer-vistools/issues/57

Update bigdataviewer-vistools: 1.0.0-beta-30 -> 1.0.0-beta-31

---

.github/build.sh
.github/setup.sh
.github/workflows/build.yml
tests/run.sh

Add melting-pot to CI

---

pom.xml

Bumping to the latest patch release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-11-1/74557 for full details of the changes included.

Bump Bio-Formats version to 6.11.1

---

pom.xml

Manage version of org.json:json

---

pom.xml

This fixes issues on Window (0.3.1 and 0.2.0 respectively) and updates Scala to 3.3.0 LTS

Bump scala-scripting to 0.3.2 and add script-editor-scala 0.2.1

---

pom.xml

Bumping to the latest patch release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-6-14-0/83316 for full details of the changes included.

Bump Bio-Formats version to 6.14.0

---

pom.xml

Bumping to the latest patch release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-7-0-0/84452 for full details of the changes included.

Bump Bio-Formats version to 7.0.0

---

pom.xml

Update various omero-dependencies

Bump omero deps

---

pom.xml

Bumping to the latest patch release of Bio-Formats. See https://forum.image.sc/t/release-of-bio-formats-7-0-1/87542 for full details of the changes included.

Bump Bio-Formats version to 7.0.1

---

pom.xml

Related work:
https://github.com/saalfeldlab/n5/pull/111
https://github.com/JaneliaSciComp/n5-zstandard

Add dependency management for com.github.luben.zstd-jni

---

pom.xml

Bumping to the latest release of Bio-Formats. See [here](https://forum.image.sc/t/release-of-bio-formats-7-2-0/91983) for full details of the changes included.

Bump Bio-Formats version to 7.2.0

---

pom.xml

see https://forum.image.sc/t/updating-ejml-0-25-to-ejml-0-41/87468/12

ejml 0.25 -> 0.41

---

pom.xml

bump n5-aws-s3 to 4.1.2

---

pom.xml

Bumping to the latest release of Bio-Formats. See [here](https://forum.image.sc/t/release-of-bio-formats-7-3-1/99018) for full details of the changes included.

Bump Bio-Formats version to 7.3.1

---

pom.xml

See https://www.openmicroscopy.org/2024/10/24/bio-formats-8-0-0.html for a summary of changes.

Update to Bio-Formats 8.0.0 and ome-common 6.0.24

---

pom.xml

See https://forum.image.sc/t/release-of-bio-formats-8-0-1/105143 and https://bio-formats.readthedocs.io/en/stable/about/whats-new.html#november.

Bump Bio-Formats version to 8.0.1

---

pom.xml

Version bump for BoneJ, bringing it up to date with scijava 40.0.0

BoneJ v7.0.20

---

pom.xml

Bump after release of BF 8.1.1, similar to https://github.com/scijava/pom-scijava/pull/285#.
There are no other dependencies to update as per https://bio-formats.readthedocs.io/en/stable/about/whats-new.html#march
Thank you

Update to Bio-Formats 8.1.1
